import pandas as pd

# Hedef Yatırım listesi (örnek veri, senin elindekilerle genişletilecek)
hedef_yatirim_data = [
   ("Nace Kodu","Faaliyet Alanı","Özel Şartlar"),
("A*******","TARIM, ORMANCILIK VE BALIKÇILIK",""),
("01.19.99","Başka yerde sınıflandırılmamış tek yıllık diğer bitkisel ürünlerin yetiştirilmesi","1) Sera Yatırımlarında; a) 1 ve 2. Bölgelerde asgari 20 dekar, b) 3. Bölgede asgari 15 dekar, c) 4 ve 5. Bölgelerde asgari 10 dekar, d) 6. Bölgede asgari 5 dekar ve üzeri olması şartı aranır. 2) Yapay ışıkla fotosentez sağlanan kontrollü bitkisel üretim yatırımlarında katmanlarının toplam alanının asgari 1.000 m2 olması şartı aranır. Diğer yatırımlar desteklenmez."),
("01.41.31","Sütü sağılan büyükbaş hayvan yetiştiriciliği (sütü için inek ve manda yetiştiriciliği)","a) 1, 2 ve 3. Bölgelerde asgari 500 adet/dönem damızlık veya süt yönlü büyükbaş hayvan yetiştiriciliği şartı aranır.b) 4 ve 5. Bölgelerde asgari 300 adet/dönem damızlık veya süt yönlü büyükbaş hayvan yetiştiriciliği şartı aranır.c) 6. Bölgede asgari 150 adet/dönem damızlık veya süt yönlü büyükbaş hayvan yetiştiriciliği şartı aranır.Ayrıca, tevsi ve komple yeni yatırım cinsindeki yatırımlar, yem bitkileri yetiştiriciliği ve/veya yemtesisi ve/veya süt işleme yatırımları ile entegre edilebilir."),
("01.42.09","Diğer sığır ve manda yetiştiriciliği (sütü için yetiştirilenler hariç)","a) 1, 2, 3, 4 ve 5. Bölgelerde asgari 500 adet/dönem et yönlü büyükbaş hayvan yetiştiriciliği şartı aranır.b) 6. Bölgede asgari 150 adet/dönem et yönlü büyükbaş hayvan yetiştiriciliği şartı aranır.Ayrıca, tevsi ve komple yeni yatırım cinsindeki yatırımlar; yem bitkileri yetiştiriciliği ve/veya yem tesisi ve/veya kesimhane yatırımları ile entegre edilebilir."),
("01.45.01","Koyun ve keçi (davar) yetiştiriciliği (işlenmemiş süt, kıl, tiftik, yapağı, yün vb. üretimi dahil)","a) 1, 2 ve 3. Bölgelerde asgari 2.500 adet/dönem damızlık veya et yönlü veya süt yönlü küçükbaş hayvan yetiştiriciliği şartı aranır. b) 4 ve 5. Bölgelerde asgari 1.500 adet/dönem damızlık veya et yönlü veya süt yönlü küçükbaş hayvan yetiştiriciliği şartı aranır.c) 6. Bölgede asgari 1.000 adet/dönem damızlık veya et yönlü veya süt yönlü küçükbaş hayvan yetiştiriciliği şartı aranır.Ayrıca, tevsi ve komple yeni yatırım cinsindeki yatırımlar; yem bitkileri yetiştiriciliği ve/veya yem tesisi ve/veya et yönlü küçükbaş hayvan yetiştiriciliği yatırımları kesimhane ve/veya süt yönlü küçükbaşhayvan yetiştiriciliği yatırımları süt işleme yatırımları ile entegre edilebilir."),
("01.47.01","Kümes hayvanlarının yetiştirilmesi (tavuk, hindi, ördek, kaz ve beç tavuğu vb.)","a)  Damızlık kümes hayvanları yetiştiriciliğinin kuluçkahane ile entegre olması şartı aranır.b) 1, 2, 3, 4 ve 5. Bölgelerde asgari 200.000 adet/dönem et yönlü kümes hayvanları yetiştiriciliğinin kesimhane ile entegre olması şartı aranır.c)  6. Bölgede asgari 100.000 adet/dönem et yönlü kümes hayvanları yetiştiriciliğinin kesimhane ile entegre olması şartı aranır.d) 1, 2, 3, 4 ve 5. Bölgelerde asgari 200.000 adet/dönem yumurta yönlü kümes hayvanları yetiştiriciliği şartı aranır.e) 6. Bölgede asgari asgari 100.000 adet/dönem yumurta yönlü kümes hayvanları yetiştiriciliği şartı aranır.Ayrıca, tevsi ve komple yeni yatırım cinsindeki yatırımlar; yem tesisi ve/veya et yönlü kümes hayvanları yetiştiriciliği yatırımları ileri işleme ve/veya soğuk hava deposu, yumurta yönlü kümes hayvanları yetiştiriciliği yatırımları soğuk hava deposu ve/veya yumurta tasnif- paketleme yatırımları ile entegre edilebilir."),
("01.47.03","Kümes hayvanlarından yumurta üretilmesi","a)  Damızlık kümes hayvanları yetiştiriciliğinin kuluçkahane ile entegre olması şartı aranır.b) 1, 2, 3, 4 ve 5. Bölgelerde asgari 200.000 adet/dönem et yönlü kümes hayvanları yetiştiriciliğinin kesimhane ile entegre olması şartı aranır.c)  6. Bölgede asgari 100.000 adet/dönem et yönlü kümes hayvanları yetiştiriciliğinin kesimhane ile entegre olması şartı aranır.d) 1, 2, 3, 4 ve 5. Bölgelerde asgari 200.000 adet/dönem yumurta yönlü kümes hayvanları yetiştiriciliği şartı aranır.e) 6. Bölgede asgari asgari 100.000 adet/dönem yumurta yönlü kümes hayvanları yetiştiriciliği şartı aranır.Ayrıca, tevsi ve komple yeni yatırım cinsindeki yatırımlar; yem tesisi ve/veya et yönlü kümes hayvanları yetiştiriciliği yatırımları ileri işleme ve/veya soğuk hava deposu, yumurta yönlü kümes hayvanları yetiştiriciliği yatırımları soğuk hava deposu ve/veya yumurta tasnif- paketleme yatırımları ile entegre edilebilir."),
("03.2****","Su ürünleri yetiştiriciliği","Tevsi ve komple yeni yatırım cinsindeki yatırımlar, balık yemi tesisi ile entegre edilebilir."),
("B*******","MADENCİLİK VE TAŞ OCAKÇILIĞI","Maden  Kanununda  tanımlanan  I.  grup  madenler,  altın madenciliği, mıcır yatırımları ve rödovans sözleşmesine istinaden  gerçekleştirilecek  madencilik  yatırımları  hariç olmak  üzere  müracaat  sahibi  firma  adına  düzenlenmiş işletme  ruhsatı  ve  işletme  iznine  haiz  maden  istihraç yatırımları  ve/veya  maden  işleme  yatırımları,  Maden Kanununa  istinaden  düzenlenmiş  geçerli  arama  ruhsatı veya sertifikasına sahip yatırımcıların ruhsatlı sahalarında yapacağı  maden  arama  yatırımları  ile  ham  petrol  ve doğalgaz    çıkarımı    yatırımları    desteklenir.    II.grup madenlerde istihraç yatırımları, aynı il sınırları içinde ve işleme     yatırımları     ile     entegre     olması     kaydıyla desteklenebilir. Ancak, İstanbul ilinde gerçekleştirilecek yatırımlar desteklenmez."),
("C*******","İMALAT",""),
("10.1****","Etin işlenmesi ve saklanması ile et ürünlerinin imalatı","10.12.04 hariç"),
("10.20***","Balık, kabuklu deniz hayvanları ve yumuşakçaların işlenmesi ve saklanması","10.20.06 ve 10.20.08 hariç"),
("10.3****","Sebze ve meyvelerin işlenmesi ve saklanması","Sadece sarartma ve mumlama işlemi içeren meyve ve/veya sebze yatırımları desteklenmez."),
("10.4****","Bitkisel ve hayvansal sıvı ve katı yağların imalatı","10.41.11 hariç"),
("10.5****","Süt ürünleri ve yenilebilir buz imalatı","5 ton/gün altındaki kapasiteye sahip süt işleme yatırımları desteklenmez"),
("10.61.01","Kahvaltılık tahıl ürünleri ile diğer taneli tahıl ürünlerinin imalatı (buğday, yulaf, mısır, çavdar vb. ezmeleri ile mısır gevreği ve patlamış mısır dahil)","Özel şart bulunmamaktadır."),
("10.61.07","Ön pişirme yapılmış veya başka şekilde hazırlanmış tane halde hububat imalatı (bulgur dahil, mısır hariç)","Özel şart bulunmamaktadır."),
("10.61.90","Dövülmüş diğer tahıl ürünlerinin imalatı (bulgur ve irmik hariç)","Özel şart bulunmamaktadır."),
("10.62.05","Glüten imalatı","Özel şart bulunmamaktadır."),
("10.62.06","Mısır yağı imalatı","Özel şart bulunmamaktadır."),
("10.72***","Peksimet, bisküvi, dayanıklı pastane ürünleri ve kek imalatı","Kadayıf ve yufka üretimi konusundaki yatırımlar desteklenmez."),
("10.73***","Makarna, şehriye, kuskus ve benzeri unlu mamullerin imalatı","Özel şart bulunmamaktadır."),
("10.8****","Diğer gıda maddelerinin imalatı","Küp şeker üretimi, 10.89.01 ve 100 Milyon TL üzerindeki tevsi ve modernizasyon yatırımları hariç olmak üzere 10.83.01 kodları desteklenmez."),
("10.92***","Ev hayvanları için hazır gıda imalatı","Özel şart bulunmamaktadır."),
("11******","İçeceklerin imalatı","11.01.01, 11.01.02, 11.05 ve 11.06 hariç"),
("13******","Tekstil ürünlerinin imalatı","500 Milyon TL üzerindeki modernizasyon yatırımları hariç olmak üzere 13.10.12 ve 100 Milyon TL üzerindeki modernizasyon yatırımları hariç olmak üzere 13.92.06 kodları desteklenmez."),
("14******","Giyim eşyalarının imalatı","Özel şart bulunmamaktadır."),
("15******","Diğer malzemelerden deri ve ilgili ürünlerin imalatı","Derinin tabaklanmasına yönelik yatırımlar sadece organize sanayi bölgelerinde teşvik edilir."),
("16******","Ağaç, ağaç ürünleri ve mantar ürünleri imalatı (mobilya hariç); saz, saman ve benzeri malzemelerden örülerek yapılan eşyaların imalatı","16.11.03 hariç"),
("17******","Kağıt ve kağıt ürünlerinin imalatı","6 ncı bölge yatırımları hariç olmak üzere sadece kağıt hamurundan başlayan asgari 30 Milyon TL tutarındaki yatırımlar desteklenir. 17.21, 17.22.04, 17.24 kodlarından yapılacak yatırımlarda kağıt hamurundan başlama şartı aranmaz."),
("18******","Kayıtlı medyanın basılması ve çoğaltılması","Sabit yatırım tutarı 100 Milyon TL ve üzerindeki tevsi ve modernizasyon yatırımları desteklenir."),
("19******","Kok kömürü ve rafine edilmiş petrol ürünleri imalatı","Özel şart bulunmamaktadır."),
("20******","Kimyasalların ve kimyasal ürünlerin imalatı","Özel şart bulunmamaktadır."),
("21******","Temel eczacılık ürünlerinin ve eczacılığa ilişkin preparatların (müstahzarların) imalatı","Özel şart bulunmamaktadır."),
("22.1****","Kauçuk ürünlerin imalatı","22.11.19 hariç"),
("22.2****","Plastik ürünlerin imalatı","Sabit yatırım tutarı 100 Milyon TL ve üzerindeki yatırımlar desteklenir."),
("23******","Diğer metalik olmayan mineral ürünlerin imalatı","23.12.03, 23.32, 23.5, 23.6, 23.7 ve 23.99.05 hariç"),
("24.10.05","Sıcak haddelenmiş demir veya çelikten bar ve çubukların üretilmesi (inşaat demiri dahil)","Sadece parlatılmış çubuk üretimi desteklenir."),
("24.10.08","Demir cevherinin doğrudan indirgenmesiyle elde edilen demirli ürünler ve diğer sünger demir ürünlerinin imalatı ile elektroliz veya diğer kimyasal yöntemlerle istisnai saflıkta demir üretilmesi","Özel şart bulunmamaktadır."),
("24.10.12","Ferro alaşımların imalatı (ferro manganez, ferro silisyum, ferro siliko manganez, ferro krom ve diğerleri)","Yüksek karbonlu ferro manganez hariç."),
("24.4****","Değerli ana metaller ve diğer demir dışı metallerin imalatı","Özel şart bulunmamaktadır."),
("24.5****","Metal döküm sanayii","Özel şart bulunmamaktadır."),
("25******","Fabrikasyon metal ürünleri imalatı (makine ve teçhizat hariç)","Özel şart bulunmamaktadır."),
("26******","Bilgisayarların, elektronik ve optik ürünlerin imalatı","Fotovoltaik güneş paneli üretimi yatırımları, üretim süreci ingot dilimleme aşamasından veya öncesindeki bir aşamadan başlayarak üretilen güneş hücresi ile entegre olması halinde ve hücre üretim kapasitesini aşmamak kaydıyla desteklenebilir"),
("27******","Elektrikli teçhizat imalatı","Özel şart bulunmamaktadır."),
("28******","Başka yerde sınıflandırılmamış makine ve ekipman imalatı","Özel şart bulunmamaktadır."),
("29******","Motorlu kara taşıtı, treyler (römork) ve yarı treyler (yarı römork) imalatı","29.20.06 hariç"),
("30******","Diğer ulaşım araçlarının imalatı","Tersane yatırımları ve 30.99.02 kodundaki yatırımlar hariç. Yat inşa yatırımlarında yat boyunun asgari 24 metre olması şartı aranır."),
("31******","Mobilya imalatı","31.00.06 ve 31.00.09 hariç"),
("32******","Diğer imalatlar","32.99.18, 32.99.19 ve 32.99.99 hariç"),
("33.12.03","Motor ve türbinlerin onarım ve bakımı (hidrolik, rüzgar, gaz, su, buhar türbinleri) (gemi ve tekne motorları, motorlu kara taşıtı ve motosiklet motorları hariç)","Özel şart bulunmamaktadır."),
("33.16***","Sivil hava taşıtları ve uzay araçlarının onarım ve bakımı","Özel şart bulunmamaktadır."),
("33.17.01","Demir yolu lokomotiflerinin ve vagonlarının onarım ve bakımı","Özel şart bulunmamaktadır."),
("D*******","ELEKTRİK, GAZ, BUHAR VE İKLİMLENDİRME ÜRETİMİ VE DAĞITIMI","Özel şart bulunmamaktadır."),
("35.11***","Yenilenemeyen kaynaklardan elektrik üretimi","Doğalgaza veya ithal kömüre dayalı elektrik enerjisi üretimi hariç olmak üzere elektrik enerjisi üretimi yatırımları desteklenir. Güneş enerjisinden elektrik üretimi yatırımlarında; modernizasyon niteliğindeki yatırımlar ile 240 KW altı kapasitedeki (çatı dâhil) güneş enerjisinden elektrik üretimi yatırımlar desteklenmez."),
("35.12***","Yenilenebilir kaynaklardan elektrik üretimi","Doğalgaza veya ithal kömüre dayalı elektrik enerjisi üretimi hariç olmak üzere elektrik enerjisi üretimi yatırımları desteklenir. Güneş enerjisinden elektrik üretimi yatırımlarında; modernizasyon niteliğindeki yatırımlar ile 240 KW altı kapasitedeki (çatı dâhil) güneş enerjisinden elektrik üretimi yatırımlar desteklenmez."),
("35.14.06","Elektrik enerjisinin dağıtımı (üretim kaynağından veya iletim sisteminden son kullanıcıya iletim sistemiyle taşınan elektrik enerjisi dağıtım sisteminin işletilmesi)","Özel şart bulunmamaktadır."),
("35.15.01","Elektrikli araçlar ve elektronik cihazlar için şarj istasyonlarının işletilmesi","Tebliğ ile belirlenecek şartları sağlayan yatırımlar desteklenir."),
("35.16***","Elektriğin depolanması","Özel şart bulunmamaktadır."),
("35.22.01","Ana şebeke üzerinden gaz yakıtların dağıtımı (her çeşit gazlı yakıtın, ana boru sistemiyle dağıtımı ve tedariki)","Özel şart bulunmamaktadır."),
("35.24***","Gazın depolanması (şebeke tedarik hizmetlerinin bir parçası olarak)","Özel şart bulunmamaktadır."),
("E*******","SU TEMİNİ; KANALİZASYON, ATIK YÖNETİMİ VE İYİLEŞTİRME FAALİYETLERİ","Özel şart bulunmamaktadır."),
("38******","Atık toplama, geri kazanım ve bertaraf faaliyetleri","38.11.02 hariç"),
("H*******","ULAŞTIRMA VE DEPOLAMA","Özel şart bulunmamaktadır."),
("49.1****","Demir yolu ile yolcu taşımacılığı","Özel şart bulunmamaktadır."),
("49.2****","Demir yolu ile yük taşımacılığı","Özel şart bulunmamaktadır."),
("49.5****","Boru hattı taşımacılığı","Özel şart bulunmamaktadır."),
("50.10.13","Kıyı sularında yolcuların feribotlarla, kruvaziyer gemilerle ve teknelerle taşınması (deniz otobüsleri işletmeciliği dahil; uluslararası denizler ile göl ve nehirlerde yapılanlar hariç)","Gezinti amaçlı olanlar hariç"),
("50.10.16","Uluslararası denizlerde yolcuların gemilerle taşınması","Özel şart bulunmamaktadır."),
("50.20***","Deniz ve kıyı sularında yük taşımacılığı","50.20.22 hariç"),
("50.30.08","İç sularda yolcu taşımacılığı (nehir, kanal ve göllerde yapılanlar, vb.) (gezinti amaçlı olanlar dahil)","Gezinti amaçlı olanlar hariç"),
("50.40***","İç sularda yük taşımacılığı","50.40.07 hariç"),
("51******","Hava yolu taşımacılığı","51.10.02 ve 51.10.03 hariç"),
("52.10.02","Frigorifik depolama ve antrepoculuk faaliyetleri (bozulabilir gıda ürünleri dahil dondurulmuş veya soğutulmuş mallar için depolama)","Sadece 1.000 m2 üzeri soğuk hava deposu yatırımları desteklenir."),
("52.10.03","Hububat depolama ve antrepoculuk faaliyetleri (hububat silolarının işletilmesi vb.)","Sadece lisanslı depoculuk faaliyetleri desteklenir"),
("52.10.04","Petrol, petrol ürünleri, kimyasallar vb. depolama ve antrepoculuk faaliyetleri (gaz hariç)","Özel şart bulunmamaktadır."),
("52.22.06","Su yolu taşımacılığını destekleyici olarak liman ve su yollarının işletilmesi (limanların, iskelelerin, rıhtımların, su yolu havuzlarının, deniz terminallerinin vb. işletilmesi) (deniz feneri, fener dubası vb. işletilmesi hariç)","Özel şart bulunmamaktadır."),
("52.22.08","Deniz ve kıyı suları ile iç sularda kılavuzluk ve rıhtıma yanaştırma faaliyetleri (geminin havuzlanması ve havuzdan çıkarılması dahil)","Özel şart bulunmamaktadır."),
("52.23.03","Havaalanı yer hizmet faaliyetleri (kargo ve bagaj yükleme boşaltma hizmetleri hariç)","Özel şart bulunmamaktadır."),
("52.23.04","Havaalanı işletmeciliği (uçak pisti işletme, yolcu terminali ve havayolu şirketlerinin kendi bilet satış hizmetleri dahil; havaalanı yer hizmetleri ve bilet acentelerinin faaliyetleri hariç)","Özel şart bulunmamaktadır."),
("52.24***","Kargo yükleme boşaltma (elleçleme) hizmetleri","5.000 m2 kapalı alana sahip ve Antrepo Açma İzin Belgesi olan yatırımlar desteklenir. 52.24.10 kodlu yatırımlarda ayrıca L2 Belgesi aranır."),
("I*******","KONAKLAMA VE YİYECEK HİZMETİ FAALİYETLERİ","Özel şart bulunmamaktadır."),
("55.1****","Oteller ve benzeri konaklama yerleri","50 oda ve üzeri (Otel, Tatil Köyü, Butik Otel ve Özel Konaklama Tesisi desteklenir)"),
("55.90.01","Öğrenci ve işçi yurtları, pansiyonlar ve odası kiralanan evlerde yapılan konaklama faaliyetleri (tatil amaçlı olanlar hariç)","Sadece asgari 200 öğrenci kapasitesindeki Öğrenci yurtları desteklenir."),
("K*******","TELEKOMÜNİKASYON, BİLGİSAYAR PROGRAMLAMA, DANIŞMANLIK, BİLİŞİM ALTYAPISI VE DİĞER BİLGİ HİZMETİ FAALİYETLERİ","Özel şart bulunmamaktadır."),
("62.1****","Bilgisayar programlama faaliyetleri","Özel şart bulunmamaktadır."),
("63.1****","Bilgi işlem altyapısı, veri işleme, barındırma ve ilgili faaliyetler","Sadece tebliğ ile belirlenecek teknik şart ve standartları karşılayan ve asgari 500 kW kurulu güç şartını sağlayan veri merkezi yatırımları desteklenir."),
("N*******","MESLEKİ, BİLİMSEL VE TEKNİK FAALİYETLER","Özel şart bulunmamaktadır."),
("71.2****","Teknik test ve analiz faaliyetleri","71.20.05 hariç olmak üzere sadece orta yüksek teknolojili ve yüksek teknolojili ürünlere yönelik test merkezi yatırımları ile ihracatçı birliklerinin dış ticareti desteklemek amacıyla yapacakları test merkezi yatırımları desteklenir."),
("72.1****","Doğal bilimler ve mühendislikle ilgili araştırma ve deneysel geliştirme faaliyetleri","Özel şart bulunmamaktadır."),
("75.00.02","Hayvan hastanelerinin faaliyetleri (evcil hayvanlar için ambulans faaliyetleri dahil)","Özel şart bulunmamaktadır."),
("O*******","İDARİ VE DESTEK HİZMET FAALİYETLERİ","Özel şart bulunmamaktadır."),
("82.2****","Çağrı merkezlerinin faaliyetleri","Sadece 6 ncı bölgede yapılan yatırımlar desteklenir."),
("Q*******","EĞİTİM","Özel şart bulunmamaktadır."),
("85******","Eğitim","Kamu kurumları tarafından yapılan yatırımlar ile 85.32.14, 85.32.15, 85.32.16, 85.32.90, 85.33, 85.4, 85.5 ve 85.6 hariç"),
("R*******","İNSAN SAĞLIĞI VE SOSYAL HİZMET FAALİYETLERİ","Özel şart bulunmamaktadır."),
("86.1****","Hastane hizmetleri","Kamu kurumları tarafından yapılan yatırımlar hariç"),
("87******","Yatılı bakım faaliyetleri","87.9 hariç"),
("88.91***","Çocuk gündüz bakım (kreş) faaliyetleri","Özel şart bulunmamaktadır.")


]

df_hedef_yatirim = pd.DataFrame(hedef_yatirim_data, columns=[
    "NACE KODU", "Faaliyet Alanı", "Özel Şartlar"
])
