oncelikli_yatirim_secim_listesi = [
        "a) Dijital Dönüşüm Programı veya Yeşil Dönüşüm Programı kapsamında desteklenmesine karar verilen yatırımlar.",
    "b) Teknoloji Hamlesi Programı kapsamında yayımlanan öncelikli ürün listesinde belirtilen yüksek teknolojili ürünlerin üretimine yönelik yatırımlar ile asgari 500 milyon TL tutarındaki yüksek teknolojili ürünlerin üretimine yönelik yatırımlar.",
    "c) İstanbul ilinde gerçekleştirilecek olan yatırımlar hariç olmak üzere; Teknoloji Hamlesi Programı kapsamında yayımlanan öncelikli ürün listesinde belirtilen orta yüksek teknolojili ürünlerin üretimine yönelik yatırımlar ile asgari 1 milyar TL tutarındaki orta yüksek teknolojili ürünlerin üretimine yönelik yatırımlar.",
    "ç) Müteharrik karakterli yatırımlar hariç olmak üzere; 6 ncı bölgede yapılan yatırımlar, geçici 3 üncü ve geçici 4 üncü maddeler kapsamında değerlendirilen yatırımlar.",
    "d) Savunma Sanayii Başkanlığından alınacak proje onayına istinaden gerçekleştirilecek savunma alanındaki yatırımlar.",
    "e) İmalat sanayii işletmelerinin öz tüketimine yönelik olarak gerçekleştirilecek enerji üretimi faaliyeti kapsamında bağlantı anlaşmasındaki sözleşme gücü ile sınırlı olmak kaydıyla, güneş enerjisine dayalı elektrik üretim tesisi yatırımları ile rüzgâr enerjisine dayalı elektrik üretim tesisi yatırımları.",
    "f) Enerji ve Tabii Kaynaklar Bakanlığı tarafından düzenlenen geçerli bir maden işletme ruhsatı ve izni kapsamında 3213 sayılı Maden Kanununun 2 nci maddesinin 4-b grubunda yer alan madenlerin girdi olarak kullanıldığı elektrik üretimi yatırımları.",
    "g) Nükleer enerji santrali yatırımları.",
    "ğ) Asgari 500 milyon TL tutarındaki, sıvılaştırılmış doğal gaz (LNG) yatırımları ve yer altı doğal gaz depolama yatırımları.",
    "h) Maden istihraç yatırımları ve/veya maden işleme yatırımları.",
    "ı) 3213 sayılı Kanuna istinaden düzenlenmiş geçerli arama ruhsatı veya sertifikasına sahip yatırımcıların ruhsatlı sahalarında yapacağı maden arama yatırımları.",
    "i) Ar-Ge yatırımları.",
    "j) Ar-Ge merkezi veya tasarım merkezlerinde yürütülen Ar-Ge veya tasarım projeleri ile ilişkili İstanbul ili dışındaki yatırımlar.",
    "k) Teknolojik Ürün Deneyim Belgesi düzenlenmiş ürünlerin üretimine yönelik yatırımlar.",
    "l) Orta yüksek teknolojili ve yüksek teknolojili ürünlere yönelik test merkezi yatırımları ile ihracatçı birliklerinin dış ticareti desteklemek amacıyla yapacakları test merkezi yatırımları.",
    "m) Asgari yatırım tutarı şartı aranmaksızın ihtisas serbest bölgelerinde gerçekleştirilecek yazılım ve bilişim ürünleri üretimi yatırımları.",
    "n) Tebliğ ile belirlenecek teknik şart ve standartları karşılayan ve asgari 3 megavat kurulu güç şartını sağlayan veri merkezi yatırımları.",
    "o) Tebliğ ile belirlenecek teknik şart ve standartlara göre hizmet veren veri merkezlerinde bulut hizmeti sağlayıcıları tarafından yapılacak asgari 200 milyon TL tutarındaki yatırımlar.",
    "ö) Çevre İzin ve Lisans Yönetmeliği kapsamında çevre lisansına tabi yatırımlar.",
    "p) Demiryolu, denizyolu veya havayolu ile taşımacılık yatırımları.",
    "r) Yük taşımacılığına yönelik liman yatırımları (yat limanı ve marina hariç).",
    "s) Kültür ve turizm koruma ve gelişim bölgelerinde, turizm merkezlerinde, Kültür ve Turizm Bakanlığının bağlı/ilgili alan başkanlıkları sınırları içerisinde veya termal turizm konusundaki turizm konaklama yatırımları.",
    "ş) Özel sektör tarafından gerçekleştirilecek olan, kreş ve gündüz bakım evleri, okul öncesi eğitim, ilkokul, ortaokul ve lise eğitim yatırımları ile hava araçlarının kullanım, tamir ve bakımına yönelik eğitim yatırımları.",
    "t) Asgari 100 kişi ve üzeri kapasiteli yaşlı ve/veya engelli bakım merkezleri.",
    "u) Lisanslı depoculuk yatırımları.",
    "ü) 25 dekar ve üzeri yurtiçinde üretilen sera teknolojilerini ihtiva eden otomasyona dayalı (bilgisayar kontrollü iklimlendirme, sulama, gübreleme ve ilaçlama sistemi ihtiva eden) topraksız sera yatırımları.",
    "v) Sanayi sicil belgesine sahip mevcut tesislerde yapılacak deprem veya yangın riskine karşı yapılan yatırımlar.",
    "y) Sanayi Genel Müdürlüğünden alınacak uygunluk yazısına istinaden gerçekleştirilecek afet teknolojileri alanındaki yatırımlar.",
    "z) Hayır."
]
